# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            冉杰的博客
nickname:		  风淋天下
description:      '一个程序员的自我修炼之路'
url:              http://quranjie.github.io
baseurl:          /

author:
  name:           'ranjie'
  url:            https://github.com/quranjie

paginate:         10

# Gems
gems: [jekyll-paginate]

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/quranjie/quranjie.github.io
