# Dependencies
markdown:         kramdown

# Setup
title:            冉杰的博客
description:      '一个程序员的自我修炼之路'
url:              http://quranjie.github.io
baseurl:          /

author:
  name:           'ranjie'
  url:            https://github.com/quranjie

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/quranjie/quranjie.github.io
